//! Declarative graph schema: types, versioning, and the IDL parser/validator
//! contract described in spec §3 ("Modèle de données").
//!
//! This crate is the single source of truth referenced by ingestion
//! validation, Iceberg table generation, DSL static validation (§7.2) and
//! typed client bindings (§3.4) — every other crate depends on it, it
//! depends on nothing else in this workspace.

mod evolution;
mod grammar;
mod parser;

pub use evolution::SpecSchemaEvolution;
pub use parser::PestSchemaParser;

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt;

/// Global node identifier (§3.3). Either derived from a stable business key
/// (hash) or generated by the ingestion pipeline — the crate doesn't care
/// which; both are opaque `u64`s to everything downstream.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct NodeId(pub u64);

/// Global edge identifier (§3.3), independent of `(src, dst, type)` to
/// support multigraphs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct EdgeId(pub u64);

/// A node's single, exact type (§3.1 — no multi-label; multi-facet entities
/// are modeled as edges between distinct nodes, see spec §3.1).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Label(pub String);

/// An edge's single, exact relationship type (§3.1).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct EdgeType(pub String);

/// Scalar property types supported by the schema (§3.2).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ScalarType {
    Int64,
    Float64,
    Bool,
    String,
    Timestamp,
    Bytes,
    List(Box<ScalarType>),
    /// Dense fixed-dimension vector, reserved for future use (embeddings) —
    /// deliberately out of scope for v1 indexing (§5.2, §13).
    Vector {
        dim: u32,
    },
}

/// A single property declaration on a node or edge type.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertyDef {
    pub name: String,
    pub ty: ScalarType,
    pub optional: bool,
    /// Whether a property index (§5.2) is built for this property. Kept
    /// explicit/opt-in per property to bound index memory cost, rather than
    /// indexing every property by default.
    pub indexed: bool,
}

/// Declaration of one node label (§3.1, §3.4).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeDef {
    pub label: Label,
    pub properties: Vec<PropertyDef>,
}

/// Declaration of one edge type, with typed endpoints (§3.1).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeDef {
    pub edge_type: EdgeType,
    pub from: Label,
    pub to: Label,
    pub properties: Vec<PropertyDef>,
}

/// A single versioned schema (§3.5 — `schema graph_v1`, `graph_v2`, ...).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Schema {
    pub version: String,
    pub nodes: BTreeMap<Label, NodeDef>,
    pub edges: BTreeMap<EdgeType, EdgeDef>,
}

impl Schema {
    pub fn node_def(&self, label: &Label) -> Option<&NodeDef> {
        self.nodes.get(label)
    }

    pub fn edge_def(&self, edge_type: &EdgeType) -> Option<&EdgeDef> {
        self.edges.get(edge_type)
    }
}

#[derive(Debug, thiserror::Error)]
pub enum SchemaError {
    #[error("malformed schema IDL: {0}")]
    Parse(String),
    #[error("incompatible schema evolution from {from} to {to}: {reason}")]
    IncompatibleEvolution {
        from: String,
        to: String,
        reason: String,
    },
    #[error("unknown label: {0:?}")]
    UnknownLabel(Label),
    #[error("unknown edge type: {0:?}")]
    UnknownEdgeType(EdgeType),
    #[error("value for {property} does not match declared type")]
    TypeMismatch { property: String },
}

/// Parses the declarative IDL (§3.4) into a [`Schema`]. See
/// [`PestSchemaParser`] for the concrete `pest`-backed implementation.
pub trait SchemaParser {
    fn parse(&self, idl_source: &str) -> Result<Schema, SchemaError>;
}

/// Classifies a schema change as compatible (applied without a blocking
/// migration, mirroring Iceberg's native column-add evolution) or
/// incompatible (property removed/renamed/retyped — requires the explicit
/// migration process left as `TBD` in spec §3.5/§13). See
/// [`SpecSchemaEvolution`] for the concrete implementation.
pub trait SchemaEvolution {
    fn diff(&self, from: &Schema, to: &Schema) -> EvolutionKind;
}

#[derive(Debug, Clone, PartialEq)]
pub enum EvolutionKind {
    Compatible,
    Incompatible { reasons: Vec<String> },
}

impl fmt::Display for Label {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl fmt::Display for EdgeType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
