//! *(task CL1)* Stable hash function backing `PartitionHasher`.
//!
//! **Decision (CL1):** `xxh3_64` (via the `xxhash-rust` crate) over the
//! node id's little-endian byte representation.
//!
//! Why xxh3 rather than a cryptographic hash (SipHash/SHA) or the
//! placeholder modulo:
//! - Not a security boundary — `node_id -> partition_id` only needs a
//!   good *distribution*, not collision resistance against an adversary
//!   (spec §8.3 already puts AuthN/AuthZ out of scope, so there is no
//!   attacker deliberately choosing `node_id`s to skew partition load).
//! - xxh3 is one of the fastest hashes available for small fixed-size
//!   keys (8 bytes here) — this runs on every single node visited during
//!   a traversal (partition resolution on `ResolveStart` and on every
//!   `RemoteRef` hop, §7.4), so it has to be negligible next to the
//!   network round-trip it gates.
//! - Well-distributed enough in practice that `hash % n_partitions`
//!   doesn't need a second mixing step (unlike `id.0 % n_partitions`,
//!   the placeholder it replaces, which skews badly whenever `node_id`s
//!   are dense/sequential — exactly the case for the "generated by a
//!   counter" half of the double `node_id` mode, spec §3.3).
//! - **Must never change** once a graph exists (spec §6.2: `n_partitions`
//!   and the hash function together fix `hash(node_id) % n_partitions`
//!   for the graph's lifetime — changing either silently reassigns every
//!   node to a different logical partition, which is exactly the
//!   "rehash" the sur-partitionnement design deliberately avoids).
//!
//! **Revision:** the actual formula now lives in
//! `graph_schema::partitioning` (see that module's doc comment) so that
//! `graph-index`'s builder (task IX3) can share it without depending on
//! this crate, which would be a dependency cycle
//! (`graph-cluster -> graph-index`). This module re-exports it so
//! `PartitionHasher::partition_of` in `lib.rs` and this file's tests
//! don't need to change.

#[allow(unused_imports)] // used by this module's own tests below
pub use graph_schema::partitioning::stable_hash;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stable_hash_is_deterministic() {
        assert_eq!(stable_hash(42), stable_hash(42));
    }

    #[test]
    fn stable_hash_differs_for_sequential_ids() {
        // The point of not using a placeholder modulo: sequential ids
        // must not collapse to sequential (i.e. predictably skewed)
        // hash outputs.
        let hashes: Vec<u64> = (0..8).map(stable_hash).collect();
        let mut sorted = hashes.clone();
        sorted.sort_unstable();
        assert_ne!(
            hashes, sorted,
            "hash output should not preserve input order"
        );
    }

    #[test]
    fn stable_hash_distributes_across_a_small_partition_count() {
        // Not a rigorous statistical test — just a smoke test that 1000
        // sequential ids don't all collapse onto one or two of 16
        // partitions, which `id % 16` would do for the "generated by a
        // dense counter" node_id case (spec §3.3).
        let n_partitions = 16u64;
        let mut counts = vec![0u32; n_partitions as usize];
        for id in 0..10_000u64 {
            let p = (stable_hash(id) % n_partitions) as usize;
            counts[p] += 1;
        }
        let min = *counts.iter().min().unwrap();
        let max = *counts.iter().max().unwrap();
        // 10_000 / 16 = 625 expected per bucket; allow generous slack
        // rather than asserting a tight statistical bound.
        assert!(min > 400, "bucket too empty: {counts:?}");
        assert!(max < 900, "bucket too full: {counts:?}");
    }
}
