[package]
name = "graph-query"
version.workspace = true
edition.workspace = true

[dependencies]
graph-schema.workspace = true
graph-dsl.workspace = true
graph-index.workspace = true
graph-cluster.workspace = true
graph-storage.workspace = true
async-trait.workspace = true
thiserror.workspace = true
futures.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true }
