[workspace]
resolver = "2"
members = [
    "crates/graph-schema",
    "crates/graph-storage",
    "crates/graph-index",
    "crates/graph-dsl",
    "crates/graph-query",
    "crates/graph-proto",
    "crates/graph-cluster",
    "crates/graph-observability",
    "examples/demo",
    "examples/ingest-cloud-cost",
    "examples/query-client",
    "bin/graph-partition-node",
    "bin/graph-coordinator",
    "bin/graph-viewer-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[workspace.dependencies]
graph-schema = { path = "crates/graph-schema" }
graph-storage = { path = "crates/graph-storage" }
graph-index = { path = "crates/graph-index" }
graph-dsl = { path = "crates/graph-dsl" }
graph-query = { path = "crates/graph-query" }
graph-proto = { path = "crates/graph-proto" }
graph-cluster = { path = "crates/graph-cluster" }
graph-observability = { path = "crates/graph-observability" }

tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
tonic = "0.11"
prost = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.7"
tower-http = { version = "0.6", features = ["fs"] }
thiserror = "1"
arc-swap = "1"
tracing = "0.1"
pest = "2"
pest_derive = "2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
chrono = { version = "0.4", default-features = false, features = ["std"] }

tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
opentelemetry = "0.24"
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.17", features = ["http-proto", "reqwest-client"] }
tracing-opentelemetry = "0.25"
prometheus = "0.13"
